method: grid
metric: 
  goal : maximize 
  name : avg_total_reward
parameters :
  num_layers :
    values : [1] 
  hidden_units : 
    values : [64]
  num_iterations :
    values : [3000]
  evaluation_episodes :
    values : [1000]
  gamma :
    values : [0.99]
  