method: grid
metric: 
  goal : maximize 
  name : avg_total_reward
parameters :
  q1_num_layers :
    values : [2] 
  q1_hidden_units : 
    values : [64]
  q2_num_layers :
    values : [2] 
  q2_hidden_units : 
    values : [64]
  q3_num_layers :
    values : [2] 
  q3_hidden_units : 
    values : [64]
  q4_num_layers :
    values : [2] 
  q4_hidden_units : 
    values : [64]
  num_iterations :
    values : [200]
  evaluation_episodes :
    values : [1000]
  gamma :
    values : [0.99]
  